# You must have the following environment variable set in .env file:
#  HOST   | my.example.com   | Your Relay Server URL exactly as it is accessed by GSN Clients

version: "2"

services:
  gsn:
    container_name: gsn
    ports:
      - "443:443"
      - "80:80"
    # Make sure to replace this `build` folder with an actual image when deploying, e.g.
    # image: rly-network/jsrelay:3.0.0-beta.3
    build: ./jsrelay
    restart: on-failure

    # /app/data - relay specific folder
    # /app/config - read-only config folder
    volumes:
      - ./config:/app/config:ro
      - ./gsndata:/app/data:rw

    environment:
      url: https://${HOST}/
      port: 80
      workdir: /app/data
      config: /app/config/gsn-relay-config.json
    mem_limit: 100M
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "10"
